### ISSUE TITLE
2.0 TODOs

### ISSUE THREAD

**Issue by abbl** [abbl/electron-dove#1]
## About
As I implemented the first major version of the library, I will now proceed to work on the version 2.0.
Which will include more "quality of life" features and expose some of the library internal API.

## TODOs

- [x] Use decorators to access the Request data in controller methods and subscriber function.
```typescript
// Right now the request body gets injected automatically to controller method
// e.g

@injectable()
class Controller {
  @MessagePattern('test')
  public test(requestBody: {test: string}) {
    someServiceMethod(requestBody.test);
  }
}

// After the this feature will be implemented, accessing of the request body will look like this
// e.g

@injectable()
class Controller {
  @MessagePattern('test')
  public test(@Body() requestBody: {test: string}) {
    someServiceMethod(requestBody.test);
  }
}
```
- [x] Rebuild and expose middleware feature to high-level API.
- [x] Support middleware in DoveClient class.
- [x] Built-in class-transformer support, to convert controller params to classes provided by user.
- [x] Write unit-tests for core classes of the library.
- [x] Various refractors/improvements to the already existing codebase.
